name: Install Environment and Download Code
description: Install dependencies and download code using gclient
inputs:
  gclient_file_path:
    description: 'Path to .gclient file (relative to repository root)'
    required: true
    default: '.github/.gclient'
  install_deps_script:
    description: 'Path to install-deps.sh script (relative to repository root)'
    required: true
    default: 'tools/install-deps.sh'
runs:
  using: "composite"
  steps:
    # Step 1: 设置 SSH（如果提供了 SSH_PRIVATE_KEY）
    - name: Set up SSH
      if: ${{ env.SSH_PRIVATE_KEY != '' }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Step 2: 缓存 depot_tools
    - name: Cache depot_tools
      uses: actions/cache@v3
      with:
        path: $HOME/depot_tools
        key: ${{ runner.os }}-depot_tools-${{ hashFiles(inputs.install_deps_script) }}
        restore-keys: |
          ${{ runner.os }}-depot_tools-

    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        chmod +x ${{ inputs.install_deps_script }}
        ${{ inputs.install_deps_script }}

    # Step 4: 将 depot_tools 添加到 PATH
    - name: Add depot_tools to PATH
      run: echo "$HOME/depot_tools" >> $GITHUB_PATH

    # Step 5: 创建 code 目录并复制 .gclient 文件
    - name: Setup code directory and copy .gclient
      run: |
        mkdir -p code
        cp ${{ inputs.gclient_file_path }} code/.gclient

    # Step 6: 运行 gclient sync 下载代码
    - name: Run gclient sync
      run: |
        cd code
        gclient sync
