name: Docker Build Test
on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yoofa/ave-build:latest
    steps:
      # Step0: check repo
      - name: Check out the repo
        uses: actions/checkout@v3

      # Step1: sync full code
      - name: gclient sync full code
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          gclient sync

      # Step2: build code
      - name: 使用 GN 和 Ninja 进行编译
        run: |
          gn gen out/Default
          ninja -C out/Default
