name: Docker build
on:
  workflow_dispatch:

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      # Step0: check repo
      - name: Check out the repo
        uses: actions/checkout@v2

  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yoofa/ave-build:latest
      options: --user builduser
    env:
      PATH: /setup/depot_tools:$PATH
    steps:
      # Step1: sync full code
      - name: gclient sync full code
        shell: bash
        run: |
          gclient sync

      # Step2: build code
      - name: 使用 GN 和 Ninja 进行编译
        shell: bash
        run: |
          gn gen out/Default
          ninja -C out/Default